# Form implementation generated from reading ui file 'ui_add_car.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rented = QtWidgets.QLineEdit(parent=Form)
        self.rented.setObjectName("rented")
        self.verticalLayout.addWidget(self.rented)
        self.name_input = QtWidgets.QLineEdit(parent=Form)
        self.name_input.setObjectName("name_input")
        self.verticalLayout.addWidget(self.name_input)
        self.brand_input = QtWidgets.QLineEdit(parent=Form)
        self.brand_input.setObjectName("brand_input")
        self.verticalLayout.addWidget(self.brand_input)
        self.year_input = QtWidgets.QLineEdit(parent=Form)
        self.year_input.setObjectName("year_input")
        self.verticalLayout.addWidget(self.year_input)
        self.cost_input = QtWidgets.QLineEdit(parent=Form)
        self.cost_input.setObjectName("cost_input")
        self.verticalLayout.addWidget(self.cost_input)
        self.info_input = QtWidgets.QLineEdit(parent=Form)
        self.info_input.setObjectName("info_input")
        self.verticalLayout.addWidget(self.info_input)
        self.image_input = QtWidgets.QLineEdit(parent=Form)
        self.image_input.setObjectName("image_input")
        self.verticalLayout.addWidget(self.image_input)
        self.browse_image_button = QtWidgets.QPushButton(parent=Form)
        self.browse_image_button.setObjectName("browse_image_button")
        self.verticalLayout.addWidget(self.browse_image_button)
        self.save_button = QtWidgets.QPushButton(parent=Form)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rented.setPlaceholderText(_translate("Form", "Rented"))
        self.name_input.setPlaceholderText(_translate("Form", "Model name"))
        self.brand_input.setPlaceholderText(_translate("Form", "Brand name"))
        self.year_input.setPlaceholderText(_translate("Form", "Year"))
        self.cost_input.setPlaceholderText(_translate("Form", "Cost"))
        self.info_input.setPlaceholderText(_translate("Form", "Info"))
        self.image_input.setPlaceholderText(_translate("Form", "Image"))
        self.browse_image_button.setText(_translate("Form", "Browse Image"))
        self.save_button.setText(_translate("Form", "Save"))
