# Form implementation generated from reading ui file 'ui_edit_user.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(170, 212)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_input = QtWidgets.QLineEdit(parent=Form)
        self.login_input.setObjectName("login_input")
        self.verticalLayout.addWidget(self.login_input)
        self.password_input = QtWidgets.QLineEdit(parent=Form)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.is_admin = QtWidgets.QRadioButton(parent=Form)
        self.is_admin.setObjectName("is_admin")
        self.verticalLayout.addWidget(self.is_admin)
        self.save_button = QtWidgets.QPushButton(parent=Form)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_input.setPlaceholderText(_translate("Form", "login"))
        self.password_input.setPlaceholderText(_translate("Form", "password"))
        self.is_admin.setText(_translate("Form", "admin"))
        self.save_button.setText(_translate("Form", "Save"))
